lang: en-US
source: ./nshipster.com
destination: ./_site-nshipster.com
url: http://nshipster.com

title: NSHipster
description: "<strong>NSHipster</strong> is a journal of the overlooked bits in Objective-C, Swift, and Cocoa. Updated weekly."
permalink: /:title/
timezone: America/Los_Angeles

twitter: 629523445
facebook: 418545184954768
google: 105091289906267717942
issn: 2373-9800

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "strikethrough", "highlight", "superscript", "tables", "footnotes", "with_toc_data", "smart"]

highlighter: pygments

exclude: ["articles", "books", "training"]

gems:
  - jekyll-redirect-from

collections:
  authors:
    output: true
    permalink: /authors/:path/
  books:
    output: false

groups:
  - Cocoa
  - Objective-C
  - Swift
  - Open Source
  - Xcode
  - Miscellanea
  - Trivia

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      hiddenlang: "swift,objective-c"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"

